- name: Demo on Variables
  hosts: all
  vars:
    URL1: Play.google.com
  vars_files:
   -var.yml
  tasks:
   - name: print a variable from play
    debug:
      msg: URL = {{URL1}}
   - name: print a variable from file
    debug:
      msg: URL = {{URL2}}
   - name: print task level variable
      vars:
       URL3: task.google.com
      debug:
        msg: URL = {{URL3}}
    - name: print variable from Host file
      debug:
        msg: URL = {{URL5}}
    - name: print varibale from CLI
      debug:
        msg: URL = {{URL4}}

