- name: Installing NodeJS
  yum:
    name: 
      - nodejs
      - gcc-c++
      - make
    state: present
    
- name: Creating Roboshop App user
  user:
    name: roboshop
    
- name: Downlaoding catalogue zip file
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/catalogue/archive/main.zip
    dest: /tmp
    remote_src: yes
    
- name: Removing old file
  ansible.builtin.file:
    path: /home/roboshop/catalogue
    state: absent
    
- name: Copying extracted content to catalogue path
  ansible.builtin.copy:
    src: /tmp/catalogue-main/
    dest: /home/roboshop/catalogue/
    remote_src: yes
    owner: roboshop
    group: roboshop
    
- name: Install NodeJS packages based on package.json.
  community.general.npm:
    path: /home/roboshop/catalogue
  become_user: roboshop
  
- name: Configuring Systemd services
  copy: 
    src: systemd.service
    dest: /etc/systemd/system/catalogue.service
    
- name: Starting catalogue service
  systemd:
    name: catalogue
    state: restarted
    enabled: yes
    daemon_reload: yes